# Generated by Django 4.2.7 on 2024-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link above to read blog post', max_length=200),
        ),
    ]
