# Generated by Django 4.2.7 on 2024-06-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_category_post_author_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
