# Generated by Django 4.2.7 on 2024-06-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
