# Generated by Django 4.2.7 on 2024-06-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
