# Generated by Django 4.2.7 on 2024-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_alter_category_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
