# Generated by Django 4.2.7 on 2024-06-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
